# @package _global_
env_name: lunarlander_discrete_medium
agent_name: dqn
max_episode_steps: 1000
train_episodes: 6000
grad_clip_norm: 1

batch_size: 1024
buffer_size: 500000
hidden_dims: [256, 256] 
glie_b: 250
tau: 0.001
lr: 5e-5 
